name: auto-build
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push:

jobs:
  dummy1GoTest:
    name: dummy1GoTest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build dummy1
        run: go build -v playground/cmd/dummy1
      - name: Test Consumer
        run: go test -v ./test/dummy1/...
      - name: Race detecor dummy1
        run: go test -race ./test/dummy1/...

  dummy2GoTest:
    name: Dummy2GoTest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build dummy2
        run: go build -v router/cmd/dummy2
      - name: Test dummy2
        run: go test -v ./test/dummy2/...
      - name: Race detecor dummy2
        run: go test -race ./test/dummy2/...